server:
  port: 8108
  servlet:
    context-path: /hydosky-send
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  application:
    name: hydosky-send
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/hydosky_send?useSSL=false&useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Yangsha130333
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #驼峰下划线转换
      column-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl